### ISSUE TITLE
Issue while gradle build with godot 3.0

### ISSUE THREAD

**Issue by pintu236** [drtwisted/godot-google-play-games-services#6]
#### Issue description: 
 Can't compile this plugin with Godot 3.0 having this error,I'm compiling it along with
Godot admob.I'm using linux.
[](https://github.com/kloder-games/godot-admob)

#### Steps to reproduce:
./gradlew build
#### Actual result:
```
> Task :compileDebugJavaWithJavac
/home/pintu/Documents/git/godot/modules/godot_gpgs/android/gpgs/Client.java:155: error: cannot access zzo
        Dialog dialog = GooglePlayServicesUtil.getErrorDialog(connectionResult.getErrorCode(),
                                              ^
  class file for com.google.android.gms.common.zzo not found
/home/pintu/Documents/git/godot/modules/godot_gpgs/android/gpgs/PlayerInfo.java:120: error: cannot access zza
            return player.getLevelInfo().getCurrentLevel().getLevelNumber();
                                        ^
  class file for com.google.android.gms.common.internal.safeparcel.zza not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
```

**Comment by drtwisted** [comment]
@pintu236 Hello, this module is using old APIs which is to be deprecated (yes, I know it's in desperate need of rewrite:( ). As you can see from the stacktrace it says exactly that thing. You eather should try to compile it with suggested flags `Note: Recompile with -Xlint:deprecation for details.` or will have to use another module, until I (or somebody else, maybe you?) will rewrite the module with use of new Google API.

**Comment by pintu236** [comment]
yeah ! It is. I'll see what can i do.
